apiVersion: apps/v1
kind: Deployment
metadata:
  name: twelveshockcrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twelveshockcrm
  template:
    metadata:
      labels:
        app: twelveshockcrm
    spec:
      containers:
        - name: twelveshockcrm
          image: quarkus/twelveshockcrm
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_URI
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: DB_NAME
            - name: WOOCOMMERCE_CLIENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: woocommerce-secret
                  key: WOOCOMMERCE_CLIENT_USERNAME
            - name: WOOCOMMERCE_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: woocommerce-secret
                  key: WOOCOMMERCE_CLIENT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: twelveshockcrm-service
spec:
  type: NodePort
  selector:
    app: twelveshockcrm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080