# mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly90d2VsdmVzaG9ja2RiOlZmbUh3NlVJWHRLazp6WVRAN2NsdXN0ZXIwLnpobjZpLm1vbmdvZGIubmV0Lw==
  DB_NAME: dHdlbHZlc2hvY2tybQ==